FROM elixir:1.18-otp-27 AS builder

ENV MIX_ENV=prod

WORKDIR /app

RUN apt-get update \
        && apt-get install -y --no-install-recommends \
            git \
            build-essential \
            ca-certificates \
            zstd \
            pkg-config \
            libssl-dev \
        && rm -rf /var/lib/apt/lists/*

COPY mix.exs mix.lock ./
COPY config ./config
COPY lib ./lib

RUN mix local.rebar --force \
    && mix local.hex --force \
    && mix deps.get \
    && mix deps.compile

ENV RELEASE_DISTRIBUTION="name"

# Overriden at runtime
ENV POD_IP="127.0.0.1"

# This will be the basename of node
ENV RELEASE_NAME="flame_k8s_controller"

# This will be the full nodename
ENV RELEASE_NODE="${RELEASE_NAME}@${POD_IP}"

RUN test -d rel || mix release.init

RUN mix release flame_k8s_controller

# ---- Application Stage ----
FROM debian:bookworm-slim

RUN apt-get update \
        && apt-get install -y --no-install-recommends \
            ca-certificates \
            zstd \
            libstdc++6 \
            openssl \
            libncurses6 \
            libtinfo6 \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN chown nobody /app

# Set runner ENV
ENV MIX_ENV=prod
ENV HOME=/app

COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/bakeware/ ./

RUN mkdir -p /app/.cache/bakeware/ && chmod 777 /app/.cache/bakeware/

USER nobody

ENTRYPOINT [ "./flame_k8s_controller", "start" ] 