defmodule Mix.Tasks.Bonny.Gen.Manifest.FlameK8sControllerCustomizer do
  @moduledoc """
  Implements a callback to override manifests generated by `mix bonny.gen.manifest`
  """

  @doc """
  This function is called for every resource generated by `mix bonny.gen.manifest`.
  Use pattern matching to override specific resources.

  Be careful in your pattern matching. Sometimes the map keys are strings,
  sometimes they are atoms.

  ### Examples

  def override(%{kind: "ServiceAccount"} = resource) do
    put_in(resource, ~w(metadata labels foo)a, "bar")
  end
  """

  import YamlElixir.Sigil

  @spec override(Bonny.Resource.t()) :: Bonny.Resource.t()
  def override(%{"kind" => "Deployment"} = resource) do
    IO.inspect(resource, label: "Customizer Overrides")

    image =
      get_in(
        resource,
        [
          "spec",
          "template",
          "spec",
          "containers",
          Access.filter(&(&1["name"] == "flame-controller")),
          "image"
        ]
      )
      |> List.first()

    resource
    |> update_in(
      [
        "spec",
        "template",
        "spec",
        "containers",
        Access.filter(&(&1["name"] == "flame-controller")),
        Access.key("env", [])
      ],
      &(&1 ++ [release_cookie_env()])
    )
    |> update_in(
      ["spec", "template", "spec", Access.key("volumes", [])],
      &[
        %{"name" => "certs", "secret" => %{"secretName" => "flame-webhook-tls", "optional" => true}}
        | &1
      ]
    )
    |> put_in(
      [
        "spec",
        "template",
        "spec",
        "containers",
        Access.all(),
        "securityContext",
        "runAsUser"
      ],
      1001
    )
    |> update_in(
      [
        "spec",
        "template",
        "spec",
        "containers",
        Access.filter(&(&1["name"] == "flame-controller")),
        Access.key("volumeMounts", [])
      ],
      &[%{"name" => "certs", "mountPath" => "/mnt/cert"} | &1]
    )
    |> update_in(
      [
        "spec",
        "template",
        "spec",
        "containers",
        Access.all(),
        Access.key("volumeMounts", [])
      ],
      fn volume_mounts ->
        [%{"name" => "bakeware-cache", "mountPath" => "/app/.cache/bakeware/"} | volume_mounts]
      end
    )
    |> update_in(
      [
        "spec",
        "template",
        "spec",
        Access.key("initContainers", [])
      ],
      fn init_containers ->
        certs = %{
          "name" => "init-certificates",
          "image" => image,
          "env" => [release_cookie_env()]
          |> Kernel.++([
            %{"name" => "FLAME_BOOTSTRAP_TLS_ONLY", "value" => "true"},
            %{"name" => "FLAME_BOOTSTRAP_TLS_SECRET", "value" => "flame-webhook-tls"}
          ]),
          "volumeMounts" => [%{"name" => "bakeware-cache", "mountPath" => "/app/.cache/bakeware/"}]
        }

        [certs | init_containers]
      end
    )
    |> update_in(
      ["spec", "template", "spec", Access.key("volumes", [])],
      fn volumes ->
        [%{"name" => "bakeware-cache", "emptyDir" => %{}} | volumes]
      end
    )
    |> put_in(
      [
        "spec",
        "template",
        "spec",
        "containers",
        Access.filter(&(&1["name"] == "flame-controller")),
        "ports"
      ],
      [%{"containerPort" => 9001, "name" => "webhooks"}]
    )
  end

  def override(%{"kind" => "ClusterRole"} = resource) do
    IO.inspect(resource, label: "Customizer Overrides")

    Map.update!(resource, "rules", fn rules ->
      [
        ~y"""
        apiGroups: ["admissionregistration.k8s.io"]
        resources:
          - validatingwebhookconfigurations
          - mutatingwebhookconfigurations
        verbs: ["get", "list", "update", "patch"]
        """,
        ~y"""
        apiGroups: ["apiextensions.k8s.io"]
        resources: ["customresourcedefinitions"]
        verbs: ["get", "list", "update", "patch"]
        """
        | rules
      ]
    end)
  end

  def override(%{"kind" => "CustomResourceDefinition"} = resource) do
    IO.inspect(resource, label: "Customizer Overrides")

    resource
    |> Map.update!("metadata", fn
      %{"labels" => labels} = metadata when labels == %{} -> Map.delete(metadata, "labels")
      metadata -> metadata
    end)
    |> update_in(["spec", "versions", Access.all()], fn
      version ->
        version
        |> Enum.reject(fn
          {"additionalPrinterColumns", []} -> true
          {"deprecated", false} -> true
          _ -> false
        end)
        |> Map.new()
    end)
  end

  defp release_cookie_env do
    %{
      "name" => "RELEASE_COOKIE",
      "valueFrom" => %{
        "secretKeyRef" => %{
          "name" => "flame-erlang-cookie",
          "key" => "cookie"
        }
      }
    }
  end

  # fallback
  def override(resource), do: IO.inspect(resource, label: "Customizer Overrides")
end
